name: Labeler

on: [pull_request]

permissions:
  pull-requests: write
  issues: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR
    steps: 
      - name: Pull request size labeler
        uses: developaul/pr-size-labeler@main
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "100"
          s_max_size: "200"
          m_max_size: "300"
          l_max_size: "400"
